[
  inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: [
    export_glyphs: 1,
    glyph: :"*",
    component: 3,
    advance: 1,
    xmin: 1,
    xmax: 1,
    ymin: 1,
    ymax: 1,
    data: 1,
    name_table: 1,
    platform: 2,
    encoding: 2,
    language: 2,
    copyright: 1,
    family: 1,
    subfamily: 1,
    unique_id: 1,
    full_name: 1,
    version: 1,
    postscript_name: 1,
    trademark: 1,
    manufacturer: 1,
    designer: 1,
    description: 1,
    vendor_url: 1,
    designer_url: 1,
    license: 1,
    license_url: 1,
    typographic_family: 1,
    typographic_subfamily: 1,
    sample_text: 1,
    postscript_cid_findfont_name: 1
  ]
]
